# version: "3.8"
# services:
#   postgres:
#     container_name: container-pg
#     image: postgres
#     hostname: localhost
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: root
#       POSTGRES_DB: test_db
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     restart: unless-stopped

#   pgadmin:
#     container_name: container-pgadmin
#     image: dpage/pgadmin4
#     depends_on:
#       - postgres
#     ports:
#       - "5050:80"
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: root
#     restart: unless-stopped

# volumes:
#   postgres-data:

version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://admin:root@postgres:5432/test_db
      - FROM_EMAIL=anku130794@gmail.com
      - FROM_PASSWORD=xhlexropodjtdwbf
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - JWT_SECRET_KEY=20da24faf6b542d34131de1a27fc72806df274dfec9ae87ea70502274fb203c1
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION_MINUTES=60
    depends_on:
      - postgres
      - pgadmin
    volumes:
      - .:/app

  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  postgres_data:
